#! /bin/sh
# -*- tab-width:8; indent-tabs-mode:nil; c-basic-offset:2; -*-
# vim: set sw=2 ts=8 et:
#
# Copyright (c)
#   2014 FAU -- Joachim Falk <joachim.falk@fau.de>
#   2017 FAU -- Joachim Falk <joachim.falk@fau.de>
#   2021 FAU -- Joachim Falk <joachim.falk@fau.de>
# 
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.

GITBRANCH=""
test -f .gitbranch && GITBRANCH=`cat .gitbranch`
ORIGINGITBRANCH="origin/$GITBRANCH"

if test -d .git; then
  GITDIR=".git"
elif test -f .git; then
  GITDIR=`sed -ne '/^gitdir:/{s/^[^:]*:\s*//;p}' .git`
else
  echo "The directory `pwd` is not a git repository!"
  exit 255
fi

if grep '^ref: refs/heads/' ${GITDIR}/HEAD >/dev/null; then
  if test -n "$GITBRANCH"; then
    git branch --set-upstream-to="$ORIGINGITBRANCH" `sed -e 's/^ref: refs\/heads\///' ${GITDIR}/HEAD`
  fi
  exit 0;
fi
if test -n "$GITBRANCH"; then
  GITBRANCHTMP=""
  if test -f "${GITDIR}/refs/heads/$GITBRANCH"; then
    GITBRANCHTMP=`mktemp -u --tmpdir=${GITDIR}/refs/heads "${GITBRANCH}.XXX"`
    GITBRANCHTMP=`basename "$GITBRANCHTMP"`
    git checkout -b "$GITBRANCHTMP"
    git checkout "$GITBRANCH"
    git merge "$GITBRANCHTMP" && git branch -d "$GITBRANCHTMP"
  else
    git checkout -b "$GITBRANCH"
    git branch --set-upstream-to="$ORIGINGITBRANCH" `sed -e 's/^ref: refs\/heads\///' ${GITDIR}/HEAD`
  fi
  exit 0;
fi

echo "This project is missing .gitbranch, so I can't guess a valid branch name!"
exit -1
