#!/bin/bash

if [ $# -eq 0 ]; then
  RELEASE=`date +%y%m%d%H%M%S`
else
  RELEASE=$1
fi

if [ -z $RELEASEDIR ]; then
  RELEASEDIR=/afs/apd.pok.ibm.com/func/vlsi/eclipz/pz6/verif/pdd1/icb5/sysc/releases
fi

if ./forall-projects.sh tla changes 1>&2 | grep '^[^#]' > /dev/null; then echo "There are local changes. Exiting..."; exit 1; fi

tla tag falk@cs.fau.de--2008-ibm-cooperation/cayman-top--mainline--0.1 falk@cs.fau.de--2008-ibm-cooperation/cayman-top--mainline-snapshot--$RELEASE
tla cat-config --snap config > config-release
tla commit -s "Released version $RELEASE"

cd $RELEASEDIR

tla tla get cayman-top--mainline-snapshot--$RELEASE ICB5_SysC-$RELEASE

cd ICB5_SysC-$RELEASE
tla build-config config
./autoreconf.sh
mkdir obj32
cd obj32
./configure -C --enable-shared --disable-static
make
